USER:
  properties:	{ translateable: false, chainable: false, versionable: true }
  columns:
    username:   { type: string(50), required: true, validators: [], default: ~, values: ~ }
    password:   { type: string(64), required: true, validators: [], default: ~, values: ~ }
    email:      { type: string(50), required: true, validators: [], default: ~, values: ~ }

SUBSCRIBER:
  properties:	{ translateable: false, chainable: false, versionable: false }
  columns:
    email:      { type: string(50), required: true, validators: [], default: ~, values: ~ }

PERMISSION:
  properties:	{ translateable: true, chainable: false, versionable: false }
  columns:
    description:{ type: clob, required: true, validators: [], default: ~, values: ~ }

CATEGORY:
  properties:	{ translateable: true, chainable: false, versionable: false }
  columns:
    description:{ type: clob, required: true, validators: [], default: ~, values: ~ }

PGROUP:
  properties:	{ translateable: true, chainable: false, versionable: false }
  columns:
    description:{ type: clob, required: true, validators: [], default: ~, values: ~ }

PAGE:
  properties:	{ translateable: true, chainable: false, versionable: true }
  columns:
    view:		{ type: clob, required: true, validators: [], default: ~, values: ~ }
    controller:	{ type: clob, required: true, validators: [], default: ~, values: ~ }

TEMPLATE:
  properties:	{ translateable: true, chainable: false, versionable: true }
  columns:
    templateview:{ type: clob, required: true, validators: [], default: ~, values: ~ }
    view:		{ type: clob, required: true, validators: [], default: ~, values: ~ }
    controller:	{ type: clob, required: true, validators: [], default: ~, values: ~ }
    structure:	{ type: clob, required: true, validators: [], default: ~, values: ~ }

FORM:
  properties:	{ translateable: true, chainable: false, versionable: true }
  columns:
    preprocess:	{ type: clob, required: true, validators: [], default: ~, values: ~ }
    structure:	{ type: clob, required: true, validators: [], default: ~, values: ~ }
    process:	{ type: clob, required: true, validators: [], default: ~, values: ~ }
    view:		{ type: clob, required: true, validators: [], default: ~, values: ~ }

WALL:
  properties:	{ translateable: false, chainable: true, versionable: false }
  columns:
    message:	{ type: clob, required: true, validators: [], default: ~, values: ~ }

RESOURCE:
  properties:	{ translateable: true, chainable: true, versionable: true }
  columns:
    description:{ type: clob      , required: true, validators: [], default: ~, values: ~ }
    filename:	{ type: string(50), required: true, validators: [], default: ~, values: ~ }
    oldfilename:{ type: string(50), required: true, validators: [], default: ~, values: ~ }
    filetype:	{ type: string(20), required: true, validators: [], default: ~, values: ~ }
    filesize:	{ type: integer(10), required: true, validators: [], default: ~, values: ~ }

EMAIL:
  properties:	{ translateable: false, chainable: false, versionable: false }
  columns:
    mailfrom:	{ type: string(50), required: true, validators: [], default: ~, values: ~ }
    mailto:		{ type: clob, required: true, validators: [], default: ~, values: ~ }
    mailcc:		{ type: clob, required: true, validators: [], default: ~, values: ~ }
    mailbcc:	{ type: clob, required: true, validators: [], default: ~, values: ~ }
    title:		{ type: clob, required: true, validators: [], default: ~, values: ~ }
    content:	{ type: clob, required: true, validators: [], default: ~, values: ~ }

ANNOUNCEMENT:
  properties:	{ translateable: false, chainable: false, versionable: false }
  columns:
    content:	{ type: clob, required: true, validators: [], default: ~, values: ~ }